name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - ".github/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - ".github/**"
  # allow manual runs
  workflow_dispatch:

# Cancel older runs of the same ref
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-and-build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      NEXT_TELEMETRY_DISABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      # Install ALL deps (dev + prod) for lint/tsc
      - name: Install deps (clean)
        run: npm ci --no-audit --no-fund

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      # Build with prod env ONLY for this step
      - name: Build (static export)
        env:
          NODE_ENV: production
        run: npm run build

      - name: Upload static artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: static-out-${{ github.sha }}
          path: out
          if-no-files-found: ignore
          retention-days: 7
