name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  # Manual trigger from the Actions tab
  workflow_dispatch:

# Cancel older runs of same ref
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-and-build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          # LTS, matches your Cloudflare setting
          node-version: "20"
          cache: npm

      - name: Install deps (clean)
        # npm ci installs devDependencies by default
        run: npm ci

      - name: Verify eslint is present
        run: npx --no eslint -v

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Build (static export)
        run: npm run build

      - name: Upload static artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: static-out-${{ github.sha }}
          path: out
          if-no-files-found: ignore
          retention-days: 7
